import { loadConfig, repoRoot, readDock, writeDock } from '../lib/config.js';
import { log, die } from '../lib/log.js';
import * as git from '../lib/git.js';
import * as gh from '../lib/gh.js';

export default function land(args) {
  const root = repoRoot();
  const cfg = loadConfig(root);
  const issue = args.find((a) => /^\d+$/.test(a));
  if (!issue) die('Usage: drydock land <issue-number>');

  const dock = readDock(issue, root);
  if (!dock) die(`No dock for issue #${issue}.`);

  if (git.isDirty(dock.worktree)) {
    die('Worktree has uncommitted changes.', 'Commit them inside the dock first.');
  }

  const head = git.headSha(dock.worktree);

  // --- Gate verification. This is the whole point of Drydock. ---
  const problems = [];
  for (const name of cfg.gates) {
    const g = dock.gates[name];
    if (!g) problems.push(`"${name}" has not run`);
    else if (g.verdict !== 'pass') problems.push(`"${name}" did not pass`);
    else if (g.sha !== head) problems.push(`"${name}" is STALE (passed @ ${g.sha.slice(0, 8)}, HEAD is ${head.slice(0, 8)})`);
  }
  if (problems.length) {
    log.err(`Dock #${issue} cannot land:`);
    problems.forEach((p) => log.dim('• ' + p));
    log.dim('Re-run the failing gate against the current HEAD.');
    process.exit(1);
  }

  log.ok(`All gates green @ ${head.slice(0, 8)}`);

  const receipt = renderReceipt(dock, cfg, head);
  const body = `Closes #${issue}\n\n${receipt}`;

  if (args.includes('--dry-run')) {
    log.warn('Dry run — nothing pushed. PR body would be:');
    log.raw('\n' + body + '\n');
    return;
  }

  const push = git.pushBranch(dock.branch, dock.worktree);
  if (!push.ok) die('Push failed.', push.err);
  log.ok(`Pushed ${dock.branch}`);

  if (gh.available()) {
    const pr = gh.createPr(
      { title: `${dock.title} (#${issue})`, body, base: dock.base, head: dock.branch },
      dock.worktree
    );
    if (pr.ok) { dock.pr = pr.out; log.ok(`PR opened: ${pr.out}`); }
    else log.warn(`PR not created automatically: ${pr.err}`);
  } else {
    log.warn('gh not installed — open the PR manually with this body:');
    log.raw('\n' + body + '\n');
  }

  dock.status = 'landed';
  dock.landedAt = new Date().toISOString();
  writeDock(dock, root);
  log.dim(`Clean up when merged: drydock clean ${issue}`);
}

// Plain bold text, not an HTML comment: the GitHub MCP server strips HTML
// comments from PR bodies, which silently destroyed the marker CI gates on.
// `.github/workflows/drydock-gates.yml` must detect exactly this line.
const RECEIPT_MARKER = '**drydock-receipt:v1**';

function renderReceipt(dock, cfg, head) {
  const rows = cfg.gates.map((n) => {
    const g = dock.gates[n];
    return `| ${n} | ✅ ${g.verdict} | \`${g.sha.slice(0, 8)}\` | ${g.by} | ${g.note || '—'} |`;
  }).join('\n');
  return [
    RECEIPT_MARKER,
    '',
    '### Drydock gate receipt',
    '',
    '| Gate | Verdict | Commit | By | Note |',
    '|---|---|---|---|---|',
    rows,
    '',
    `Head at land time: \`${head}\``,
    '',
    '<sub>Generated by Drydock. CI verifies these gates match the PR head SHA.</sub>',
  ].join('\n');
}
