import { loadConfig, repoRoot, readDock, writeDock } from '../lib/config.js';
import { log, die } from '../lib/log.js';
import { parseArgs } from '../lib/args.js';
import * as git from '../lib/git.js';
import * as gh from '../lib/gh.js';
import * as notify from '../notify.js';
import { isAgent } from './gate.js';

export default function land(args) {
  const root = repoRoot();
  const cfg = loadConfig(root);

  // A mistyped `--dry-run` used to be discarded, turning a preview into a real
  // push, a real PR and — now — armed auto-merge.
  const cli = parseArgs(args, { flags: ['--dry-run'] });
  if (cli.unknown.length) die(`Unknown option: ${cli.unknown.join(', ')}`, 'Usage: drydock land <issue> [--dry-run]');

  const issue = cli.positionals.find((a) => /^\d+$/.test(a));
  if (!issue) die('Usage: drydock land <issue-number> [--dry-run]');

  const dock = readDock(issue, root);
  if (!dock) die(`No dock for issue #${issue}.`);

  if (git.isDirty(dock.worktree)) {
    die('Worktree has uncommitted changes.', 'Commit them inside the dock first.');
  }

  const head = git.headSha(dock.worktree);

  // --- Gate verification. This is the whole point of Drydock. ---
  const problems = [];
  for (const name of cfg.gates) {
    const g = dock.gates[name];
    if (!g) problems.push(`"${name}" has not run`);
    else if (g.verdict !== 'pass') problems.push(`"${name}" did not pass`);
    else if (g.sha !== head) problems.push(`"${name}" is STALE (passed @ ${g.sha.slice(0, 8)}, HEAD is ${head.slice(0, 8)})`);
  }
  if (problems.length) {
    log.err(`Dock #${issue} cannot land:`);
    problems.forEach((p) => log.dim('• ' + p));
    log.dim('Re-run the failing gate against the current HEAD.');
    process.exit(1);
  }

  log.ok(`All gates green @ ${head.slice(0, 8)}`);

  const receipt = renderReceipt(dock, cfg, head);
  const body = `Closes #${issue}\n\n${receipt}`;

  if (cli.flags.has('--dry-run')) {
    log.warn('Dry run — nothing pushed. PR body would be:');
    log.raw('\n' + body + '\n');
    return;
  }

  const push = git.pushBranch(dock.branch, dock.worktree);
  if (!push.ok) die('Push failed.', push.err);
  log.ok(`Pushed ${dock.branch}`);

  if (gh.available()) {
    const pr = gh.createPr(
      { title: `${dock.title} (#${issue})`, body, base: dock.base, head: dock.branch },
      dock.worktree
    );
    if (pr.ok) {
      dock.pr = pr.out;
      log.ok(`PR opened: ${pr.out}`);
      notify.lifecycle(cfg, issue, prOpenedComment(dock, pr.out, head), root);
      armAutoMerge(dock, cfg, pr.out);
    } else log.warn(`PR not created automatically: ${pr.err}`);
  } else {
    log.warn('gh not installed — open the PR manually with this body:');
    log.raw('\n' + body + '\n');
  }

  dock.status = 'landed';
  dock.landedAt = new Date().toISOString();
  writeDock(dock, root);
  log.dim(`Clean up when merged: drydock clean ${issue}`);
}

// Plain bold text, not an HTML comment: the GitHub MCP server strips HTML
// comments from PR bodies, which silently destroyed the marker CI gates on.
// `.github/workflows/drydock-gates.yml` must detect exactly this line.
const RECEIPT_MARKER = '**drydock-receipt:v1**';

function renderReceipt(dock, cfg, head) {
  const verdicts = cfg.gates.map((n) => ({ name: n, g: dock.gates[n], agent: isAgent(dock.gates[n].by) }));
  const rows = verdicts.map(({ name, g, agent }) =>
    `| ${name} | ✅ ${g.verdict} | \`${g.sha.slice(0, 8)}\` | ${agent ? '🤖' : '👤'} ${g.by} | ${g.note || '—'} |`
  ).join('\n');

  // Who recorded a verdict changes what it is worth, so the receipt has to say
  // so at a glance. Kept out of the first three columns, which CI parses.
  const legend = verdicts.some((v) => v.agent)
    ? '🤖 recorded by an agent · 👤 recorded by a human'
    : '👤 every verdict recorded by a human';

  return [
    RECEIPT_MARKER,
    '',
    '### Drydock gate receipt',
    '',
    '| Gate | Verdict | Commit | By | Note |',
    '|---|---|---|---|---|',
    rows,
    '',
    legend,
    '',
    `Head at land time: \`${head}\``,
    '',
    '<sub>Generated by Drydock. CI verifies these gates match the PR head SHA.</sub>',
  ].join('\n');
}

function prOpenedComment(dock, url, head) {
  return [
    '### Drydock: pull request opened',
    '',
    `- **PR:** ${url}`,
    `- **Branch:** \`${dock.branch}\` → \`${dock.base}\``,
    `- **Head:** \`${head}\``,
    '',
    '<sub>Every gate passed against this commit. The receipt is in the PR body.</sub>',
  ].join('\n');
}

/**
 * Queue the merge for when the repository says it is safe.
 *
 * Drydock never issues an immediate merge: `--auto` hands the decision to
 * GitHub's branch protection. That only means anything if there is a required
 * check to wait for — `--auto` on an unprotected branch merges the instant the
 * PR opens, which would make the gates decorative. So `waitForChecks` is
 * treated as a precondition and not just a flag: with it on and no required
 * check configured, arming is refused and the PR is left for a human.
 */
function armAutoMerge(dock, cfg, ref) {
  const merge = cfg.autonomy?.merge ?? {};
  if (!merge.enabled) { log.dim('Auto-merge disabled by policy — a human merges this.'); return; }

  if (merge.waitForChecks !== false) {
    const checks = gh.requiredChecks(dock.base, dock.worktree);
    if (!checks?.length) {
      log.warn(`Auto-merge NOT armed: no required status checks on ${dock.base}.`);
      log.dim('`--auto` with nothing to wait for merges immediately and unverified.');
      log.dim('Make `drydock-gates` a required check, or set autonomy.merge.waitForChecks false.');
      return;
    }
    log.dim(`Required checks on ${dock.base}: ${checks.join(', ')}`);
  }

  const r = gh.mergePr(ref, { method: merge.method, auto: true, deleteBranch: true }, dock.worktree);
  if (r.ok) log.ok(`Auto-merge armed (${merge.method}) — GitHub merges when checks pass`);
  else log.warn(`Auto-merge not armed: ${String(r.err || '').split('\n')[0] || 'gh exited non-zero'}`);
}
